name: "This is the build workflow!"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  # JOB #1:  BUILD
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install GCC
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y gcc make

      - name: Build and Test
        run: make test


      #------------------------------------------------------
      # Makefile generates test_results in /build
      # This "prints" it to cout so the github action can see it

      - name: Show test summary
        if: always()
        run: |
          echo "=== Test Results ==="
          cat build/test_results.txt 2>/dev/null || echo "No results file found"
      

      #------------------------------------------------------
      # Artifacts

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-results-${{ github.run_number }}
          path: build/test_results.txt
          retention-days: 7

      - name: Upload build binaries
        if: success()
        uses: actions/upload-artifact@v7
        with:
          name: embutils-binaries-${{ github.run_number }}
          path: |
            build/test_ring_buffer
            build/test_crc
            build/test_bit_utils
          retention-days: 7



  # JOB #2 Static Analysis (Runs on seperate VM)
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install cppcheck
        run: sudo apt-get install -y cppcheck

      # Note to self:
      #   cppcheck does not output file (or at least non-errors to file)
      #   and piping output caused all sorts of errors.   Gave up trying to
      #   get cppcheck as an artifact.  
      - name: Run cppcheck
        run: |
          cppcheck \
            --enable=warning,style,performance \
            --error-exitcode=1 \
            --suppress=missingIncludeSystem \
            --std=c99 \
            src/ 

        